$screens = @(
    @{ title = "FlowPay Splash Screen"; image = "https://lh3.googleusercontent.com/aida/AOfcidXMylJoRJ5gS-L13_W-D--_5Z9NbTzGgamQJvjhVHx1Ir47nCmG3cJFG5p4T5WIk5jLQNg5jkfSnrToxkKpzSoK27dXTyPQaWL0lS4uwNIaEZgoLRw9y5kdFImdf1pt4q7quiqdbpT1GsGBvxFWM_ndNLLh3SaABcBLXtSJK9NIszyLQiyeNwywFfWX2WC_Od3NVoNI4NtR96rYUdi5iSTPQwZjiS5boLcnOkSvMYRzwodLvs8Y69XmqJA"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzM4YjNiOTM3NDc0MzRlYWFhNGYxYTM1MmZiNGMwMWJkEgsSBxDisaa17hwYAZIBIwoKcHJvamVjdF9pZBIVQhMyNzg3NzUwMDY5NDc0MTUwMTg0&filename=&opi=89354086" },
    @{ title = "Scan and Pay via Flow"; image = "https://lh3.googleusercontent.com/aida/AOfcidW6rl5Kcy3YCLTCCpS2wbk5EvIp_MZeDz_DQSTMXIljH3WA1ZnDfOuNkbWWWQpAOynZXoq9sLXyZVBazLxTJCJjImZMuPgMnra8Qg17FghAP9RNTCONgcI7E374j1SaHkMibSkPnp_qEW5zJOe7hFfDJ5cHuuHsqK5EvFiwiYzryn2ur_9Lu7U-BYFGIsLbkEnEk1AYX9yLqU6jLKY19DPSssd-RruluR9gT0fqYYwsx0MOZZ2zQixwIMk"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2RkMmExMmNiNjc3NjQ2OWM4NzFhMjZlZjk2YzQ4YmRiEgsSBxDisaa17hwYAZIBIwoKcHJvamVjdF9pZBIVQhMyNzg3NzUwMDY5NDc0MTUwMTg0&filename=&opi=89354086" },
    @{ title = "Set Spending Rules"; image = "https://lh3.googleusercontent.com/aida/AOfcidU7Zt0PZTYFzi_LP6FHxNPH2GqaA-C2jS1y1V6X28wvQ9dIMW7IWeLM9U3y7QZOuD96q_JATe6wZGdaafbkjgiv1LmTmwcGRJ49YgV75bCrrfvd85UUtPyZ4ox7Wlg7P_yTbYtaMUtJg5agRU_eNCSWNRe8NZTikN5cAAsXoZFUjBL-Gkfhyt7XFkusXQ72uCwnGIJFK2hpJpCs2DPQoYgSboVKbNyu9h9CJaHQPjbwVYEaW50ZJtROLls"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzQ5NDIyN2JiYmFjNDRmMmI5OTI3ZTUxNDgyMTA1OWU3EgsSBxDisaa17hwYAZIBIwoKcHJvamVjdF9pZBIVQhMyNzg3NzUwMDY5NDc0MTUwMTg0&filename=&opi=89354086" },
    @{ title = "Main Wallet Balance"; image = "https://lh3.googleusercontent.com/aida/AOfcidVj8RcoF3WpXaX2Dlo4yJ_ksnL32_J2kxsPJTwbChNMh4qhXN-Vcy8j6COkWOlLKPaygD_6iTkMvcmDe8OrcL8--2ZaiBjYnHupk9LQaBNypGcGdN7eZWwTDgKcG2p12uPV2gCWQ_ZIQ9dvxuUoz9DHBbLZPrfxs_7we_WQMoDNOpN5v1NN1eHdVKgh8ThxGHH463eAS-aXfVIj39tGs8wbi9kF4BExKrFgf8MFvZmjdvwLLLeeLac_QBI"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzA5NWVkZjNhZDFlZjRkMTA4MTgxNmNjNmM1ZjhkODUwEgsSBxDisaa17hwYAZIBIwoKcHJvamVjdF9pZBIVQhMyNzg3NzUwMDY5NDc0MTUwMTg0&filename=&opi=89354086" },
    @{ title = "FlowPay Welcome Screen"; image = "https://lh3.googleusercontent.com/aida/AOfcidXP4qI91wDHieibwvSAfDVTuU94-MhYS1xc17KQJQWx9gFJ_i4U1hOcVF93GIO97JNPuxTUEn6RKqc1zTBgBXe588XGXCRlnJ95QcIEvrcCutVl5-wXVgh8Z2-LIrNPENJ34TDhMNvbnDKJuIl5eBH-g2mqSNLGysfjU1I1NuhJAwK_lOnDCzGX76eqr5fHjdq0_77Ed0RRk0i5ahQ_sNhgtYgQYidvqiSoj9DJCxeNZcb_1OzISeokYw"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzkwNGI4NTg1YjQ2ZDRkMDM5MGI1ZTBjMDliZGYzZTNhEgsSBxDisaa17hwYAZIBIwoKcHJvamVjdF9pZBIVQhMyNzg3NzUwMDY5NDc0MTUwMTg0&filename=&opi=89354086" },
    @{ title = "Global Spending Insights"; image = "https://lh3.googleusercontent.com/aida/AOfcidXURzVR_n9A_RfvyHNetifMF_cWmX5iEve0GfugDVR3vBh8J4O1m2PwBSGKVqtgLuEsMpZXnwyWHqN0NLwEBN_l3_vxL8RYW2SuRKDrgAOxoOc3TLOKWh8TsJM1pLNR_di01sE0QXoRZDSa4YRNcGiZBUzEtKWrrpflQRA-kEIHzTjysYFV6zZgWqXoXa7jECL3iXmHCetRYoFrDK1TCAzu4T1St6IP41jWo-v3jYKDjqbnhYJfshVN1kc"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzMyYWFmZThkNGRhZTQxOGFhMWM1MTdhMjg2MDE3YjczEgsSBxDisaa17hwYAZIBIwoKcHJvamVjdF9pZBIVQhMyNzg3NzUwMDY5NDc0MTUwMTg0&filename=&opi=89354086" },
    @{ title = "FlowPay Home Dashboard"; image = "https://lh3.googleusercontent.com/aida/AOfcidVjva-5PxDfA-qWkx_qMRDSWQAk5T0uSyVv1bmMlrf6U5yO1Cy9cnC6RCI9UM8uJocGufx-MdRSfeIi5Cy42hgxSBY7SlQEKWs-fcy3fngR6INyVGVuneoBPcPQkNRhdQyCpoFIM8PspZcpJxtONIjO0SCdEKwxWMtG-Qv5P3D6_W7E-Ld29-rEvNxmQXbxhhgeuW-1C3J0HMT9495tu5pp-u--_Ny_uoBA4jVCcZGsN-zuBthdkXQD96s"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzY1ODliYjZiOGJmYjQ0YzVhZTY3ZWQ5YmI5N2U5YmFkEgsSBxDisaa17hwYAZIBIwoKcHJvamVjdF9pZBIVQhMyNzg3NzUwMDY5NDc0MTUwMTg0&filename=&opi=89354086" },
    @{ title = "Flow Details Dashboard"; image = "https://lh3.googleusercontent.com/aida/AOfcidWPIqOJ9j5BaK6SySPgt6H1KzwJDyq-vdajjHERogYghAi85v4O87xNnd-d7GVURvkGw-1uiONu06g4KJhyQZVE_VxKOMrs28TaNhvayzcGJMu5gplUeCvcNPT8aGGbv36H1xpOlpGcl7TR7On3ebYLCQdAhrulgBdz8fsLR-Jz_DLTxGspaR1GP_zcctUbTjpamoe7ZktA8z67z1drUA2waNIVEX8uDxogA47Xg7AxI1cwSmuVDl65Og"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzBhYTVhYTM3MmVlNzRhYTRhNzlkMjdhZDI1NzE5MWVmEgsSBxDisaa17hwYAZIBIwoKcHJvamVjdF9pZBIVQhMyNzg3NzUwMDY5NDc0MTUwMTg0&filename=&opi=89354086" },
    @{ title = "My Money Flows"; image = "https://lh3.googleusercontent.com/aida/AOfcidU080wdV99TWm0Rt4EqAbpnZa6MX9enKD8DrMOwE3AEesRuGAxnILPZyujD81zdu0zqMRsPNqJ8kfx7CdhToMlI0ORNofjoJL4fmMT1vQg5gjsm3ELTUlBIEWp5XLQprTelz2jQIjOayyOntwQ4zR6G8w6kp-GJ4QuTJEHPoc29bAme8dejMG2krzFXIST_fJRifGhzuvs3lFYgAEbz2UJjC7F0yS9jWob38YrWDNxymQmRmyFeaDmLcQ"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzFlMzU4NTRlYzVmYzQ4NGRhNjM1ZTI5YmRiMjY2YWI4EgsSBxDisaa17hwYAZIBIwoKcHJvamVjdF9pZBIVQhMyNzg3NzUwMDY5NDc0MTUwMTg0&filename=&opi=89354086" },
    @{ title = "Create New Flow"; image = "https://lh3.googleusercontent.com/aida/AOfcidWtzflrR-1hUwKj6pIGYxO-H9h7QXx9A_gF3qk5OhAJsX60z3xgWZ7oR_pPrL8VD_JkVOuSGCm03XbvEtMrNF7m-nBNDrnZBNUPB3RDCrVe9X4rEvMYfMtD8iB6oMXIdJ-X9qfDyi1_NLDOmVmLOELiUs3FeuhMsoJhBW5iPfTWqlOZigeyLn2riqrPt1Ux9KN5unLBQegNwtuxm0rBNdd4QtR4oR-9h6C4HDg61NoTJdWDAv2Ztap9G4M"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzAxYjZlYzM4NGUwYTQ4MDk4YTZjMzIzNTIzMmVjZDVhEgsSBxDisaa17hwYAZIBIwoKcHJvamVjdF9pZBIVQhMyNzg3NzUwMDY5NDc0MTUwMTg0&filename=&opi=89354086" }
)

mkdir c:\Users\Digitization\Desktop\Flowpay\screens -ErrorAction SilentlyContinue | Out-Null
foreach ($screen in $screens) {
    # remove spaces and make lowercase for better naming
    $title = $screen.title -replace ' ', '_'
    $title = $title.ToLower()
    Write-Host "Downloading $title..."
    curl.exe -s -L -o "c:\Users\Digitization\Desktop\Flowpay\screens\$title.png" $screen.image
    curl.exe -s -L -o "c:\Users\Digitization\Desktop\Flowpay\screens\$title.html" $screen.html
}
Write-Host "Download Complete"
